### ISSUE TITLE
Updated Homebridge and Plejd causes Homebridge to restart

### ISSUE THREAD

**Issue by vannman** [Herlix/homebridge-plejd#10]
**Describe The Bug:**

I updated Homebridge and had to delete Plejd and then reinstall it due to incompatibility in versions of Node.js. After I reinstalled it and configured it Homebridge continuously restarts.

**To Reproduce:**

See above.

**Expected behavior:**

Homebridge should not restart continuously.

**Logs:**
[12/27/2022, 8:55:32 PM] TypeError: Cannot read properties of undefined (reading 'length')
    at new PlejdPlatform (/homebridge/node_modules/homebridge-plejd/src/plejdPlatform.ts:34:33)
    at /homebridge/node_modules/homebridge/src/server.ts:474:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/homebridge/node_modules/homebridge/src/server.ts:401:27)
    at Server.start (/homebridge/node_modules/homebridge/src/server.ts:176:29)
[12/27/2022, 8:55:32 PM] Got SIGTERM, shutting down Homebridge...
[12/27/2022, 8:55:32 PM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/homebridge/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/homebridge/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/homebridge/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:513:28)
    at process.emit (/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: homebridge-plejd v1.2.5
* **Homebridge Version**: 1.6.0
* **Node.js Version**: v18.12.1
* **NPM Version**: 
* **Operating System**: Ubuntu Focal Fossa (20.04.5 LTS) / Docker

**Comment by Herlix** [comment]
Hey! 

Sorry for the way too late response. 

Have you tried a newer version? :)
